### PR TITLE
feat: support (at least) dual themes

### PR DESCRIPTION
**Pull request by Barbapapazes**
Hello 👋

This PR adds the support for dual themes in Shiki. This is very useful when a website have both a light and a dark theme.

With this feature, developers can still specifies a single theme but also two themes using an associative array.

In `shiki.js`, I use both variables `theme` and `themes` to align with the original Shiki API.

related to https://shiki.style/guide/dual-themes
fix https://github.com/spatie/shiki-php/discussions/22

_I'm sorry for the formatting stuff in the JS files but I could open another PR to add a JS formatter._

_I'm not a PHP expert and I'm not sure how to solve this type issue._

### CODE REVIEW

**Comment by riasvdv** [comment]
Can you rebase on the main branch? I've updated the github actions to drop PHP 7.4 support

**Comment by riasvdv** [comment]
Thanks!

**Comment by Barbapapazes** [comment]
> Thanks!

That was quick! Thanks! I will open PRs in related packages to make it available to `shiki-laravel`.

**Comment by Barbapapazes** [comment]
I've update `laravel-markdown` to my website and I could have make a mistake.

With dual theme, I should not use `color:#<color>;--shiki-dark:#<color>` because the only way to overwrite the default theme is to use `!important` in the CSS. I verify the source code of Shiki website and both light and dark must be put through variables and them apply using CSS.

```css
.dark .vp-code span {
  color: var(--shiki-dark, inherit);
}

html:not(.dark) .vp-code span {
  color: var(--shiki-light, inherit);
}
``` 

With the current implementation, the developer has to define `!important` to make sure the stylesheet overwrite the inline `style`.

We could support a new option: https://shiki.style/guide/dual-themes#without-default-color to avoid this.

**Pull request merged**
